export const Injectable = () => (target: any) => target;
export const OnModuleInit = () => (target: any) => target;
export const Module = () => (target: any) => target;
export const Controller = () => (target: any) => target;
export const Get = () => (target: any) => target;
export const Post = () => (target: any) => target;
export const Put = () => (target: any) => target;
export const Delete = () => (target: any) => target;
export const Body = () => (target: any) => target;
export const Query = () => (target: any) => target;
export const Req = () => (target: any) => target;
export const Param = () => (target: any) => target;
export const Res = () => (target: any) => target;
export const Optional = () => () => undefined;
export const UsePipes = () => (target: any) => target;
export const HttpCode = () => (target: any) => target;
export const HttpStatus = {};
export const NotFoundException = class extends Error {};
export const BadRequestException = class extends Error {};
export const ConflictException = class extends Error {};
export const UnauthorizedException = class extends Error {};
export const ForbiddenException = class extends Error {};
export const InternalServerErrorException = class extends Error {};
export const Logger = class {
  log = jest.fn();
  error = jest.fn();
  warn = jest.fn();
  debug = jest.fn();
  verbose = jest.fn();
  static info = jest.fn();
  static error = jest.fn();
  static warn = jest.fn();
  static debug = jest.fn();
  static verbose = jest.fn();
};
export const Default = () => (target: any) => target;
export const UseInterceptors = () => (target: any) => target;
export const forwardRef = () => (target: any) => target;
export const All = () => (target: any) => target;
export const ParseIntPipe = class {};
export const UseGuards = () => (target: any) => target;
export const UseFilters = () => (target: any) => target;
export const SetMetadata = () => (target: any) => target;
export const Cache = () => (target: any) => target;
